### ISSUE TITLE
App takes over my camera immediately upon opening

### ISSUE THREAD

**Issue by thelifeandtimes** [holium/campfire#1]
**Describe the feature you'd like**
Upon opening the app from grid and sitting on the "Gather Around" screen, the app requests access to my camera. This request seems reasonable at this moment in time, but then it actively turns on my camera and leaves it on even if I am not actively calling. It would be preferable for the camera to only turn on / be claimed by %campfire when I am actively calling someone else.

**Is your feature request related to a problem? Please describe.**
Roughly speaking, this could create a perception of a privacy problem. 

**Additional context**
Google Meet is some decent prior art on this with their 'home screen' frame.

**Comment by datryn-ribdun** [comment]
I believe recent versions of campfire have stopped doing this. Permission for camera+mic should only happen when dialing a ship, shouldn't happen on the home screen. If you're seeing differently, please give more details about your browser and OS.

**Comment by thelifeandtimes** [comment]
I believe you are correct. This issue can probably be closed. Great work on this.
